### ISSUE TITLE
Using weights trained here with Darknet?

### ISSUE THREAD

**Issue by alexander-hamme** [experiencor/keras-yolo3#11]
Hi, I successfully trained this keras yolo3 network on my own custom dataset and it is giving me very good results, however the network takes up to 2 seconds just to generate predictions on each image. 

(This is specifically the time for `boxes = get_yolo_boxes....` to run, not any of the extra stuff)

Is it possible to speed up predictions in any way, or even use these weights with the straight C version of Darknet? 

Thanks a lot.

**Comment by experiencor** [comment]
@alexander-hamme I'm not sure why it's so slow in your case. In my case, it's run with 7fps on video. I used Geforce 850.

**Comment by alexander-hamme** [comment]
Strange, I am using a GeForce GTX 1070 and it always takes at least 1.5 seconds to find boxes...

**Comment by JaspervDalen** [comment]
are you sure you are running on gpu? Because those are times I get on CPU
