### ISSUE TITLE
Conversion into tensorflow pb model

### ISSUE THREAD

**Issue by akbargumbira** [experiencor/keras-yolo3#114]
Hi, I am converting the trained keras model into tensorflow pb with the exact same YOLO model as in this repository. The last output tensor's name is 'output_node_0'. But it's quite hard to get the tensor names of the other two predictions i.e. https://github.com/experiencor/keras-yolo3/blob/master/yolo.py#L294 and https://github.com/experiencor/keras-yolo3/blob/master/yolo.py#L321.
Can someone tell?

Thanks

**Comment by akbargumbira** [comment]
Nevermind, I managed to do it. Cheers

**Comment by abdou31** [comment]
Hello, can you please tell me what you do to find the tensors name?
