### ISSUE TITLE
After 3 hours of training on raccoon dataset, accuracy not good.

### ISSUE THREAD

**Issue by creotiv** [experiencor/keras-yolo3#12]
So my question how long does it take to train model from scratch? I was using SSD512 before this, and it gives me good result after 14hours.

**Comment by experiencor** [comment]
I haven't check raccoon but kangaroo working well.

**Comment by creotiv** [comment]
How long does it take to train it?

**Comment by chintan5750** [comment]
what should be the minimum configuration of laptop  to train model ?

**Comment by creotiv** [comment]
I was training model on CARPRK(aerial parked cars) dataset 14hours on GTX 960M 4GB
Loss 5.05 and result is nothing. I tested it on racoon for 3 hours to see if the model converges, but also not get any results(even on trained data). 
So that's why asking, cause i don't know is this normal behavior of Yolo3, or there is a bug somewhere.

**Comment by experiencor** [comment]
I don't know. I get the best result with raccoon. Check out the readme page.
