### ISSUE TITLE
Problem of understanding the transformations of the outputs

### ISSUE THREAD

**Issue by oli37** [experiencor/keras-yolo3#132]
Hi, 
I'm trying to implement YOLOv3 with guidance of this project and struggle to unterstand the following transformations in the **decode_netout** function.
[https://github.com/experiencor/keras-yolo3/blob/master/yolo3_one_file_to_detect_them_all.py](url)

```
 netout[..., :2] = _sigmoid(netout[..., :2])
 netout[..., 4:] = _sigmoid(netout[..., 4:])
 netout[..., 5:] = netout[..., 4][..., np.newaxis] * netout[..., 5:]
 netout[..., 5:] *= netout[..., 5:] > obj_thresh
```
According to [https://towardsdatascience.com/yolo-v3-object-detection-53fb7d3bfe6b](url) the output of the each of the three detection scales should contain 3 boxes * (4+1+80)=255 values.
So, every box size should contain 85 values, the fist 4 the position (x, y), height and weight, the 5th the objectness score and the rest 80 classes one-hot encoded.

`[x, y, h, w] [s] [c1, c2, .., c80]`

Could someone please explain what's happening here? Shouldn't we use sigmoid over the first 4 and the objectness score? 

Thanks in advance :)

**Comment by JingchangHuang** [comment]
I have the same question, does anyone can help explain？

**Comment by JingchangHuang** [comment]
@oli37 have you solve this question？
