### ISSUE TITLE
Image resize

### ISSUE THREAD

**Issue by robinenrico** [experiencor/keras-yolo3#176]
I do not completely understand the use of Image resize. I had the train_times set to 3 and noticed that each epoch outputs a different number of times the resize step (variable between 1-3). 

<img width="325" alt="Screenshot 2019-03-20 at 13 57 48" src="https://user-images.githubusercontent.com/48655808/54685884-3743cf80-4b18-11e9-867e-8b96c97d5457.png">

Besides this, is it possible to remove the resize at runtime if the input size is always fixed? It seems to use a lot of resources of the CPU and results in the GPU being idle for most of the time?

**Comment by kabrau** [comment]
In generator.py got image input size and it is changed every 10 batches, it is good for the training.
