### ISSUE TITLE
KeyError: 'cache_name'

### ISSUE THREAD

**Issue by anuragcp** [experiencor/keras-yolo3#178]
I trying to train annotated dataset of ALPR, but always caught error...

Traceback (most recent call last):
  File "train.py", line 280, in <module>
    _main_(args)
  File "train.py", line 178, in _main_
    config['train']['cache_name'],
KeyError: 'cache_name'

**Comment by RiaanLab** [comment]
Same here. :-(

**Comment by anuragcp** [comment]
Problem solved 👍 
Note : 
Delete the file given in the place of cache in config.json, or put new file name instead of previous. This problem comes if you are using new dataset with new attributes.
