### ISSUE TITLE
Backend weights

### ISSUE THREAD

**Issue by nassarofficial** [experiencor/keras-yolo3#183]
Hello the backend weights seem to have been moved or deleted. When I goto the OneDrive link I get this error:

> This item might not exist or is no longer available

**Comment by JannikSt** [comment]
@nassarofficial 
wget friendly link: https://s3-ap-southeast-1.amazonaws.com/deeplearning-mat/backend.h5

_Originally posted by @tlkh in https://github.com/experiencor/keras-yolo3/issues/146#issuecomment-457815554_

**Comment by nassarofficial** [comment]
thanks a lot!

**Comment by NanoLsk** [comment]
> @nassarofficial
> wget friendly link: https://s3-ap-southeast-1.amazonaws.com/deeplearning-mat/backend.h5
> 
> _Originally posted by @tlkh in [#146 (comment)](https://github.com/experiencor/keras-yolo3/issues/146#issuecomment-457815554)_

Do you know what is the difference between backend.h5 and yolo.weights?
Can I convert yolo.weights to *.h5?
Thanks

**Comment by asetkn** [comment]
> > @nassarofficial
> > wget friendly link: https://s3-ap-southeast-1.amazonaws.com/deeplearning-mat/backend.h5
> > _Originally posted by @tlkh in [#146 (comment)](https://github.com/experiencor/keras-yolo3/issues/146#issuecomment-457815554)_
> 
> Do you know what is the difference between backend.h5 and yolo.weights?
> Can I convert yolo.weights to *.h5?
> Thanks

Readme on thins repo explains how to do it
https://github.com/qqwweee/keras-yolo3
