### ISSUE TITLE
Not Output from predict.py

### ISSUE THREAD

**Issue by cgens** [experiencor/keras-yolo3#189]
I'm running predict.py on a windows machine using Anaconda and the script runs but I don't get any output. I get what seem to be normal messages:

UserWarning: No training configuration found in save file: the model was *not* compiled. Compile it manually.
  warnings.warn('No training configuration found in save file: '

**Comment by kabrau** [comment]
This message, don't is a problem, please, send a snapshot with all messages of predict.py

**Comment by cgens** [comment]
Here's the messages I get:

![image](https://user-images.githubusercontent.com/47367311/59929772-2781a300-9407-11e9-8a1b-983448a26323.png)

Here is my config file:

![raccoon_config](https://user-images.githubusercontent.com/47367311/59929862-4c761600-9407-11e9-90b7-861e45b77547.PNG)

**Comment by kabrau** [comment]
You need to inform in  -i  the folder name, not the image name
And, inform -o the folder to images result (images with printed boxes)

**Comment by cgens** [comment]
Thanks @kabrau, I made some progress as it creates a picture in the output folder but no bounding box, the screenshot is below:

![image](https://user-images.githubusercontent.com/47367311/59932723-6dda0080-940d-11e9-9afa-8e7a68f96909.png)

**Comment by kabrau** [comment]
Please tell me about your mAP 
You can get mAP with evaluate.py

**Comment by cgens** [comment]
A quick update I can run predict.py on the images in the train_image_folder and get bounding boxes but not on a random image.

**Comment by kabrau** [comment]
For one image, you need to alter the predict.py or put one image in a new folder and predict from new folder.

**Comment by cgens** [comment]
Thank you @kabrau! I figured it out
