### ISSUE TITLE
error when run   “ python yolo3_one_file_to_detect_them_all.py -w yolov3.weights -i dog.jpg ”

### ISSUE THREAD

**Issue by shensheng27** [experiencor/keras-yolo3#19]
loading weights of convolution #1
loading weights of convolution #2
loading weights of convolution #3
loading weights of convolution #4
Traceback (most recent call last):
  File "yolo3_one_file_to_detect_them_all.py", line 440, in <module>
    _main_(args)
  File "yolo3_one_file_to_detect_them_all.py", line 411, in _main_
    weight_reader.load_weights(yolov3)
  File "yolo3_one_file_to_detect_them_all.py", line 67, in load_weights
    size = np.prod(norm_layer.get_weights()[0].shape)
AttributeError: 'NoneType' object has no attribute 'get_weights'

using python3.6.1 keras 2.0.3 tf 1.4.1  

os.environ["CUDA_DEVICE_ORDER"]="PCI_BUS_ID"
os.environ["CUDA_VISIBLE_DEVICES"]="2"

have no clue to debug, thanks for hint

**Comment by shensheng27** [comment]
by catch AttributeError as well as ValueError fix this error

by the way there are other error for different meaning of  "int  / int" between python2 and python3.

thanks for the code

**Comment by ZXJxx** [comment]
@shensheng27  I have met the same problem,could you tell me the detail that how did you save this problem?Thank you very much.

loading weights of convolution #1
loading weights of convolution #2
loading weights of convolution #3
loading weights of convolution #4
Traceback (most recent call last):
  File "yolo3_one_file_to_detect_them_all.py", line 434, in <module>
    _main_(args)
  File "yolo3_one_file_to_detect_them_all.py", line 405, in _main_
    weight_reader.load_weights(yolov3)
  File "yolo3_one_file_to_detect_them_all.py", line 59, in load_weights
    size = np.prod(norm_layer.get_weights()[0].shape)
AttributeError: 'NoneType' object has no attribute 'get_weights'

ps: Ubuntu 14.04.5,python3.4,tensorflow1.3 and keras 2.0.6

**Comment by shensheng27** [comment]
just try and catch.. its long time ago and has no gurantee to work    

```
def load_weights(self, model):
        for i in range(106):
            **try:**
                conv_layer = model.get_layer('conv_' + str(i))
                print("loading weights of convolution #" + str(i))

                if i not in [81, 93, 105]:
                    norm_layer = model.get_layer('bnorm_' + str(i))

                    size = np.prod(norm_layer.get_weights()[0].shape)

                    beta  = self.read_bytes(size) # bias
                    gamma = self.read_bytes(size) # scale
                    mean  = self.read_bytes(size) # mean
                    var   = self.read_bytes(size) # variance            

                    weights = norm_layer.set_weights([gamma, beta, mean, var])  

                if len(conv_layer.get_weights()) > 1:
                    bias   = self.read_bytes(np.prod(conv_layer.get_weights()[1].shape))
                    kernel = self.read_bytes(np.prod(conv_layer.get_weights()[0].shape))
                    
                    kernel = kernel.reshape(list(reversed(conv_layer.get_weights()[0].shape)))
                    kernel = kernel.transpose([2,3,1,0])
                    conv_layer.set_weights([kernel, bias])
                else:
                    kernel = self.read_bytes(np.prod(conv_layer.get_weights()[0].shape))
                    kernel = kernel.reshape(list(reversed(conv_layer.get_weights()[0].shape)))
                    kernel = kernel.transpose([2,3,1,0])
                    conv_layer.set_weights([kernel])
            **except ValueError:
                print("no convolution #" + str(i))**  
```

**Comment by JoyceYa** [comment]
@ZXJxx This is because the `layer_idx` is not continuously defined in the `make_yolov3_model` function，so when executing the `load_weights` function, some layers will be found missing, for example, conv_4, and `except ValueError` will be excuted , the execution stops.

You can simply change the `except ValueError` to `except` to avoid the stop, the weights will still be loaded rightly, and you'll see the detection results.

I hope this solves your problem.
