### ISSUE TITLE
Got the error when training the kangaroo dataset

### ISSUE THREAD

**Issue by sjwhhhi** [experiencor/keras-yolo3#20]
> ValueError:Dimension 0 in both shapes must be equal, but are 1 and 255. Shapes are [1,1,1024,18] and [255,1024,1,1]. for 'Assign_360' (op: 'Assign') with input shapes: [1,1,1024,18], [255,1024,1,1].

 I wonder how I can solve it. Thank U

**Comment by experiencor** [comment]
the batch size must be a multiple of the number of GPUs

**Comment by sjwhhhi** [comment]
@experiencor 
Thank you for replying.
However, I used only 1GPU, and set as followed.

        "train_times":          3,
        "batch_size":           16,
        "learning_rate":        1e-4,
        "nb_epochs":            100,
        "warmup_epochs":        3,
        "ignore_thresh":        0.5,
        "gpus":                 "0",
        "tensorboard_dir":      "logs"

The problem still existed.

**Comment by experiencor** [comment]
I think you run out of GPU memory.

**Comment by illw84u** [comment]
@sjwhhhi did you solve the problem? and how?
