### ISSUE TITLE
How fit should be the bounding box to the object?

### ISSUE THREAD

**Issue by aravind3134** [experiencor/keras-yolo3#202]
I am trying to work on my own dataset using YOLO3. 

I have a couple of questions related to it.

1. How close should the annotation bounding boxes to the original object in the image. Right now, I am using bounding boxes leaving a couple of pixels around the perimeter. 

2. There are almost half of the objects that are not predicted as objects. How to minimize the false negatives? Any suggestions are welcome.

3. Any suggestions on detection of small images that are not seen in training dataset (out of range for anchor boxes)

Thanks in advance!

**Comment by kabrau** [comment]
Hi @aravind3134 

1. The closer the better, but even you have more pixels around, during the training the model should fitting/understand.

2. 
a) More samples, the more images the better, helps the model generalize. 
b) More epochs, sometimes the model takes time to fit
c) In config.json, increment "train_times", keras-yolo3 implementation uses data augment to each image, then you when incrementing "train_times" it is like to have more samples. 

3. Is easier if you increment the dataset to train with small images.
