### ISSUE TITLE
OOM when training raccoon dataset

### ISSUE THREAD

**Issue by shensheng27** [experiencor/keras-yolo3#21]
using train.py with only change dataset path, oom after print

```
Epoch 1/103
('resizing: ', 320, 320)
```

i am using tf gpu 1.4.1 keras gpu 2.1.5 python 2.7.13   single gtx1080  yolo3_one_file_to_detect_them_all is valid

**Comment by experiencor** [comment]
Run out of memory? Just reduce batch size in config.json.
