### ISSUE TITLE
Message during training 

### ISSUE THREAD

**Issue by Alex-Naxitus** [experiencor/keras-yolo3#216]
Hello, can I suppress theses messages during training ?  
Epoch bar graph is more convenient for me 
Let me know 

loss xy, wh, conf, class:       [14][1.71806908][15.8210402][1.42107522][0]
avg_obj                 [28][0.0427666865]
avg_noobj               [28][0.036989063]
avg_iou                 [28][0.199453011]
avg_cat                 [28][0]
recall50        [28][0]
recall75        [28][0]
count   [28][1]
loss xy, wh, conf, class:       [28][6.70977736][56.1825638][26.3056412][0.989425242]
avg_obj                 [56][0]
avg_noobj               [56][0.045572497]
avg_iou                 [56][0]
avg_cat                 [56][0]
recall50        [56][0]
recall75        [56][0]
count   [56][0]

**Comment by rntatsuya** [comment]
Yes, you just have to comment out the tf.Print statements in yolo.py
