### ISSUE TITLE
errorS at training 

### ISSUE THREAD

**Issue by AhmedHessuin** [experiencor/keras-yolo3#226]
i am using tensorflow/-gpu 1.14.0, keras 2.3.0 and cuda 10.1 
training on 5 images of the kangaroo with the notations from the git repo. 
mini-batch=1  and using the backend.h5 at the training.
 ===========================================================
list of the errors:-
===========================================================
===========================================================
1)OOM, out of memory when using mini-batch>1.
Limit:                  3153238425
InUse:                  3151823616
MaxInUse:               3151840512
NumAllocs:                   11629
MaxAllocSize:            743192064
===========================================================
2)Traceback (most recent call last):
  File "D:/keras-yolo3-master/keras-yolo3-master_2/train.py", line 324, in <module>
    _main_(args)
  File "D:/keras-yolo3-master/keras-yolo3-master_2/train.py", line 312, in _main_
    average_precisions = evaluate(infer_model, valid_generator)
  File "D:\keras-yolo3-master\keras-yolo3-master_2\utils\utils.py", line 48, in evaluate
    pred_boxes = get_yolo_boxes(model, raw_image, net_h, net_w, generator.get_anchors(), obj_thresh, nms_thresh)[0]
  File "D:\keras-yolo3-master\keras-yolo3-master_2\utils\utils.py", line 262, in get_yolo_boxes
    do_nms(boxes, nms_thresh)        
  File "D:\keras-yolo3-master\keras-yolo3-master_2\utils\utils.py", line 166, in do_nms
    if bbox_iou(boxes[index_i], boxes[index_j]) >= nms_thresh:
  File "D:\keras-yolo3-master\keras-yolo3-master_2\utils\bbox.py", line 57, in bbox_iou
    return float(intersect) / union
ZeroDivisionError: float division by zero

when i print the value of the union it's equal to zero !!! how can union =0?
 
==========================================================
----------------------------------------------------------------------------------------------
can you help me and thanks in advance >:^) . 
===========================================================

**Comment by SteveIb** [comment]
Hi @AhmedHessuin , How did you manage to solve it?

**Comment by AhmedHessuin** [comment]
the dividing over inf was solved from  bbox.py  changing intersected / union to 
-----------------------------
if intersected = 0 
return 0
else
 return intersected / union
------------------------------
and i beleive it  was my bad ( i think i didn't have label for every object ) 
for some reason when i use valid files with 10 anno and want to valid on 5 anno it cause an error .
