### ISSUE TITLE
Transfer learning

### ISSUE THREAD

**Issue by krishnak** [experiencor/keras-yolo3#252]
I have a question  as per Yolo V3 architecture, the detection layers have a dimension of 1xNxNx[ (number of classes+5) x3 ]

So if there are 80 classes to be trained this becomex 1xNxNx255, After training these 80 classes, If I want to train this pre-trained model to detect a new class, i.e 81st Class how can it be done?

as the model has to be redesigned as the output layers have to be changed to 1xNxNx258 

How is this done in Keras? Can you provide some code examples.

**Comment by krishnak** [comment]
Figured out

**Comment by AhmedHessuin** [comment]
@krishnak  please tell me how

**Comment by tfc-0** [comment]
@krishnak as you have solved it, can you provide a short description of how you have solved it?
