### ISSUE TITLE
gen_anchors contains hard-coded image dimensions

### ISSUE THREAD

**Issue by amandaberg** [experiencor/keras-yolo3#261]
Row 46 in gen_anchors: "out_string += str(int(anchors[i,0]*416)) + ',' + str(int(anchors[i,1]*416)) + ', '"
contains hard-coded values for image width and height. This is problematic when the function is used to generate anchors for your own dataset.

**Comment by amandaberg** [comment]
Aha, wait... I see why. Closing this issue....

**Comment by hengkokchin** [comment]
> Aha, wait... I see why. Closing this issue....

What is the reason?
