### ISSUE TITLE
Question about predict

### ISSUE THREAD

**Issue by yuyijie1995** [experiencor/keras-yolo3#29]
![2018-04-23 10-43-09](https://user-images.githubusercontent.com/30818917/39104453-62442ade-46e3-11e8-875a-51f136c38a79.png)
Firstly,I want to thank you for answering my stupid questions.There is another question:
I used the weights that I trained last night  to predict the raccoon, but on the test image ,there is only a boundingbox without label name .Is this right? And how can I get the label name?
![2018-04-23 10-50-51](https://user-images.githubusercontent.com/30818917/39104728-372b0128-46e4-11e8-8aaf-ff75ba217524.png)
This is my config.json,I do add the label name .

**Comment by experiencor** [comment]
The label is just out of the image.

**Comment by yuyijie1995** [comment]
OK，Thankyou ！

**Comment by Jasonsun1993** [comment]
@experiencor How to adjust the font sizes of labels??
