### ISSUE TITLE
Bounding box always shifted comparing to darknet results

### ISSUE THREAD

**Issue by kylehh** [experiencor/keras-yolo3#291]
Hi
I have been testing this keras implementation for last couple of weeks.
Generally speaking the inference results are great.
But I also noticed the bbox, especially for person detection, are always shifted down, missing part of the head and too much space below the foot. Today I finally compared it with the inference result using darknet, and it confirms that darknet doesn't have this issue.
I double checked that I was using the same yolo3.weights, which was trained from COCO dataset

I guess it's due to image resize or post processing issues. Any idea how to fix it?
Thanks

Inference from this Keras version ( notice the guy in black code in the middle and on the right hand side)
![keras-version](https://user-images.githubusercontent.com/24217337/87474776-468e3c80-c5e9-11ea-9e93-6816ca0662f5.jpg)
Inference from this Darknet version
![darknet-version](https://user-images.githubusercontent.com/24217337/87474787-4a21c380-c5e9-11ea-93a8-bb877d4e804a.jpg)

**Comment by hhodac** [comment]
@curvelets thanks for pointing out this issue. I also encountered the same problem as you, and found the answer in one of the medium article.
The issue lies in the decode_netout() function, please change the following code to fix the issue.
`row = i / grid_w ==> row = i // grid_w`
