### ISSUE TITLE
Error: Unable to open file (unable to open file: name = 'model.h5'

### ISSUE THREAD

**Issue by AlexBlack2202** [experiencor/keras-yolo3#3]
I run the command 

> python yolo3_one_file_to_detect_them_all.py -w yolo3.weights -i dog.jpg
and it appear the error

> OSError: Unable to open file (unable to open file: name = 'model.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)

I don't see the model.hd5 in the solution. Can you update it.

One more thing, in line 400 to 403, the code is 

> 
>  # load the weights trained on COCO into the model
>     #weight_reader = WeightReader(weights_path)
>     yolov3.load_weights("model.h5")
>     yolov3.save("backend.h5")

That mean we do not use  the input weight for predicting, insted of we use a file "model.h5"

and in line 403 yolov3.save("backend.h5"). Why we must save model to file?

Thank you very much.

**Comment by AlexBlack2202** [comment]
I have edit some thing and it worked.
in line 402 change model.h5 to backend.h5 
 yolov3.load_weights("backend.h5")
comment line 403

cast to int in line 263, 266,274 , 293.
 new_h = int((new_h * net_w)/new_w)

new_w = int((new_w * net_h)/new_h)

new_image[int((net_h-new_h)/2):int((net_h+new_h)/2),int( (net_w-new_w)/2):int((net_w+new_w)/2), :] = resized

 row = int(i / grid_w)

Now, it work.

**Comment by experiencor** [comment]
I forgot to clean up ```yolo3_one_file_to_detect_them_all.py```.
