### ISSUE TITLE
question about evaluate

### ISSUE THREAD

**Issue by yuyijie1995** [experiencor/keras-yolo3#30]
![2018-04-23 11-05-05](https://user-images.githubusercontent.com/30818917/39105080-32034c9e-46e6-11e8-861b-975ef079c6ac.png)
What is the " "cache_name": " 's function ? And what do i need to add ? a dir path?or a label name?

**Comment by shensheng27** [comment]
use to cache valid data so you don't have to parse xml all the time

**Comment by yuyijie1995** [comment]
@shensheng27  So what should I  write between quotes?Do I need to mkdir a document named cache?

**Comment by experiencor** [comment]
It's the pickle file to save the parsing result. It's saved in the same directory that contains train.py.

**Comment by yuyijie1995** [comment]
@experiencor Thank you for your prompt reply,and I do found a file named raccoon_train.pkl .Is this one ?

**Comment by experiencor** [comment]
Yes.
