### ISSUE TITLE
Littel mistake in predict file

### ISSUE THREAD

**Issue by tofahito2** [experiencor/keras-yolo3#32]
Hello, 
I found a little mistake in predict file, line 109

image_paths = [inp_file for inp_file in image_paths if (inp_file[-4:] == '.jpg' or inp_file == '.png')] 

 inp_file for png should be inp_file[-4:] . People who have png images will never predict there output. 

correct line should be 

image_paths = [inp_file for inp_file in image_paths if (inp_file[-4:] == '.jpg' or inp_file[-4:] == '.png')] 

best of luck

**Comment by experiencor** [comment]
thanks @tofahito2
