### ISSUE TITLE
Predict: Division by Zero when no object was found

### ISSUE THREAD

**Issue by vobject** [experiencor/keras-yolo3#35]
Python 3.6, Win10, GTX 1060

I've trained a model to detect a single class (similar to the examples).
When using the `predict`  script on an image where it doesn't detect any object of said class, the subsequent code for handling bounding boxes runs into a division by zero `bbox/bbox_iou()` because `union` becomes zero.
I'm not sure how to fix the underlying issue but was able to work around it.

I've worked around this by naively replacing the return statement with:
`return float(intersect) / union if union != 0 else 0.`

This get's me further but then also had to add this to `bbox/draw_boxes()`
```
if abs(box.xmin) > 1000 or abs(box.xmax) > 1000 or abs(box.ymin) > 1000 or abs(box.ymax) > 1000:
    continue
```
because the [xy]min/max values are basically invalid values (insanely small/large)

I guess somewhere before all this the boxes should have been discarded to never even reach those code paths but I'm not familiar enough to spot it.

**Comment by experiencor** [comment]
@vobject Interesting case. I never encounter this problem as the union of the boxes is usually sizable.

**Comment by vobject** [comment]
I recently used the repo again to train another object detector (great project btw 🥇) and didn't run into the originally reported issue. Maybe the latest changes (43ca57a) have fixed it but it's more likely it was some configuration/setup issue on my system. I replaced my GPU in the meantime, that's probably it.

Since noone else has reported the issue, i'd say we close it for now.

**Comment by jsdussanc** [comment]
It has happened to me, I have trained my own data without GPU and when using evaluate.py failed, debugging it both the intersection and the union is 0.

Ubuntu16 python3.5.2 tensorflow1.8 Keras2.1.6

**Comment by AhmedHessuin** [comment]
i have the same issue

**Comment by MatthiasPilz** [comment]
I also get the same error. Would be nice to reopen this thread.
