### ISSUE TITLE
Issues with training.

### ISSUE THREAD

**Issue by abramjos** [experiencor/keras-yolo3#36]
Hey man,
This is the error I am getting right now.
`Traceback (most recent call last):
  File "gen_anchors.py", line 132, in <module>
    _main_(args)
  File "gen_anchors.py", line 111, in _main_
    centroids = run_kmeans(annotation_dims, num_anchors)
  File "gen_anchors.py", line 57, in run_kmeans
    indices = [random.randrange(ann_dims.shape[0]) for i in range(anchor_num)]
  File "gen_anchors.py", line 57, in <listcomp>
    indices = [random.randrange(ann_dims.shape[0]) for i in range(anchor_num)]
  File "/home/abraham/anaconda3/envs/yolo/lib/python3.5/random.py", line 195, in randrange
    raise ValueError("empty range for randrange()")
ValueError: empty range for randrange()
`
Its due to the pkl file for the dataset. How to create pkl for the same?
What is the content for the pkl file?

*Btw its a nice repo ;), you made yolo v3 in such a short notice

**Comment by FlyEgle** [comment]
I have also the same question , how do you solve it?

**Comment by stihl1210** [comment]
@FlyEgle @abramjos 

Ok the problem is with "cache" value and config.

Please add "/" at the end of path to the directories and remove empty cache file for dataset. Try then again.

empty randrange() is caused due to no files added to list.

**Comment by liunian199** [comment]
@stihl1210  Can you describe it more in details? 
'Please add "/" at the end of path to the directories and remove empty cache file for dataset'
directories refer to which?and dataset refer to which?I have removed all pyaches but unfortunately it doesn't work

**Comment by akarshsoman** [comment]
facing the same error , please could someone explain more clearly

**Comment by BradAxl** [comment]
@stihl1210 didn't refer to pycache. When you run gen_anchors.py, it creates a pickle file (.pkl) with the name as you define in "train/cache_name". So what you have to do is just deleting that file created incorrectly, then add "/" at the end of path as @stihl1210 said and finally run gen_anchors.py again. 
Hope this can explain much better the approach to solve this issue.

**Comment by aarti95** [comment]
how to solve this issue?

**Comment by jarrettyeo** [comment]
> how to solve this issue?

For the benefit of future users, here is what you should do.

This is part of what `config.json` looks like:

```python
    "train": {
        "train_image_folder":   "yolo-training\\images\\",
        "train_annot_folder":   "yolo-training\\annotations\\",
        "cache_name":           "SOME_FILENAME.pkl",
```

In my case, I gave the wrong path for `train_image_folder` but I have already generated the cached pkl file. What I had to do is to manually delete the .pkl file from my file explorer. I reran my code and it works now. Hope this helps.
