### ISSUE TITLE
Order of anchors

### ISSUE THREAD

**Issue by RichardSieg** [experiencor/keras-yolo3#57]
Hi there! Thanks for this (also excellent) implementation of YOLOv3. One question about the order of anchors: In all your config files, the order of the anchors is *increasing* (by width). Nevertheless, in the `yolo3_one_ file..`, the anchors are in *decreasing* order. Furthermore, it seems that for the first YOLO layer (`loss_yolo_1`) the last three anchors are used and as I understood it, this layer is responsible for the small scale. Is there a mistake in my understanding or a small bug?

**Comment by darjoo** [comment]
The anchors are in correct order (Small to large, it can be reversed if the anchors used in the layers are reversed as well accordingly). 

loss_yolo_1, the "smallest" layer after all the stride 2 convolutional layers(max pooling equiv) now has feature maps 32 times smaller than the input. However, it means that each pixel represents 32 pixels in the input. As such, the same area for prediction (3x3 kernel) represents a much larger area in the input compared to loss_yolo_2 and loss_yolo_3.

loss_yolo_2 is upsampled from loss_yolo_1, as such, it is 1:16 and loss_yolo_1 is 1:8

This is at least how I understand how FPNs work in this case.
