### ISSUE TITLE
Error: OOM when allocating tensor with shape[16,256,52,52] when using python3

### ISSUE THREAD

**Issue by illw84u** [experiencor/keras-yolo3#58]
got another error : pickle protocol: 4 when using python2

is this due to the version of python?

**Comment by RichardSieg** [comment]
You have an out of memory error. This is probably caused by a too large batch size. Try a smaller one.

**Comment by illw84u** [comment]
Thanks, changing batch size from 16 to 4 solved the oom issue.

**Comment by RichardSieg** [comment]
Great. Please close the issue then :)
