### ISSUE TITLE
About cashe file and labels for training

### ISSUE THREAD

**Issue by tanakataiki** [experiencor/keras-yolo3#6]
Thanks for a great work.
I wonder 2 things that I cant understand.

1. How can i add 3 new labels in config.json the example you show was only raccoons ,but what I want to do is to add 3 labels in one picture so I guess below
"labels":    ["a","b","c"] 
Does it work?

2. the pkl file is newly added and it want on readme. So can you tell me how to make pkl files?

**Comment by experiencor** [comment]
1. It's just example. It's designed to detect any number of classes like to train on COCO or PASCAL.
2. You don't need it. It's the pickle to store parsing result so to avoid parsing the next time you run train.py. If it's not there, it's will be created automatically.

**Comment by tanakataiki** [comment]
![problem1](https://user-images.githubusercontent.com/37890520/38712129-a40706bc-3f04-11e8-9f5f-f68c19606edc.JPG)

Thanks for the reply, I tested my own voc file format dataset and I wanted to add 5 new labels but when I add 5 new class to the previous 80 classes (coco 80 + my own 5 ) then the warning that suggests there is no labels for classes. I think it's because I didn't prepare any coco labels for training. So how can it be solved?

![problem2](https://user-images.githubusercontent.com/37890520/38712238-3c9a99ca-3f05-11e8-99d5-e5018e796432.JPG)

And After that I changed to 5 class dataset and the warning didn't appear but I wonder what the number that is nest to labels like RB:81 LB:80 RF:80 LB:81
I thought it's a ID number for classes that comes from parse_voc_annotation except coco 80
But the number is doubled isn't it a problem?

**Comment by experiencor** [comment]
1. The code of the generator will break if you do. Please make sure that your dataset has images for all the labels you want to detect. It makes no sense otherwise right. So if you start with COCO dataset, just need to add the images and labels of the additional classes that you want to detect to the corresponding folders of COCO.

2. They are the counts of the labels in the dataset. Their orders do not matter. Only the sorted list of laters is returned.

**Comment by tanakataiki** [comment]
1.I wanted to reduce training time though, but thanks for explanation.
2.the result that came from mp4 video's given labels was wrong name but exact location(eg. RF->LF).
so I thought the difference between Given Labels order and Seen Labels = Overlap Labels order would be a matter.

**Comment by tanakataiki** [comment]
@experiencor 
Actually this problem isnt solved yet I assume this is caused by python version.
Do you use python 2?

**Comment by experiencor** [comment]
https://user-images.githubusercontent.com/37890520/38712129-a40706bc-3f04-11e8-9f5f-f68c19606edc.JPG

From this image, I find that your dataset has only those 5 additional labels (seen_labels). Try to delete the cache file if your dataset does have 85 labels.

I tested my code on both python2.7 and python3.6.
