### ISSUE TITLE
Not able to predict after training on custom dataset

### ISSUE THREAD

**Issue by thomasdf** [experiencor/keras-yolo3#78]
I get the following error message when running predict.py after training on a custom dataset (haven't tested one of the standard sets, but I don't think that's the issue).

```
/usr/local/lib/python2.7/dist-packages/keras/models.py:282: UserWarning: No training configuration found in save file: the model was *not* compiled. Compile it manually.
  warnings.warn('No training configuration found in save file:
```

Training ran until early stopping.

The best_weights-file is only 247 MB, which seems small. Let me know if I can give you any other information. Do you have any ideas why this might happen?

**Comment by jamartinh** [comment]
Hello @thomasdf , just ignore the message it is a warning.
It is predicting well, but be completely sure to pass the absolute (full) path of the image to predict not a relative path.

Hope this helps.

**Comment by darjoo** [comment]
And to add on, the weights file size is correct. It only contains the inference model weights and not the training model weights.

**Comment by thomasdf** [comment]
I expected there to be saved images to the same folder as the input-folder for prediction and did not know that I had to supply the -o argument with an output path to get images with boxes saved. This is why I didn't think it was predicting. Thanks for clearing things up though!

**Comment by avaghefi** [comment]
@thomasdf 
Were you able to figure out the problem. I had the exact sane problem.
