### ISSUE TITLE
Cannot download weights from onedrive, is there any other way to download?

### ISSUE THREAD

**Issue by tsycnh** [experiencor/keras-yolo3#79]
I can't access onedrive for some reason. Is it possible to publish the weights to some other cloud drive? like [Baidu disk](https://pan.baidu.com) ？

**Comment by darjoo** [comment]
I have reuploaded it here, http://www.mediafire.com/file/l1b96fk7j18yi7v/backend.h5.
Give it a try.

**Comment by darjoo** [comment]
If that solved your issue, it would be great if you could close this issue. Otherwise let me know if you need more help :)

**Comment by tsycnh** [comment]
thanks for your help, closing the issue right now.@darjoo
