### ISSUE TITLE
ZeroDivisionError: float division by zero

### ISSUE THREAD

**Issue by chintan5750** [experiencor/keras-yolo3#8]
getting ZeroDivisionError: float division by zero on function bbox_iou while running python yolo3_one_file_to_detect_them_all.py -w yolo3.weights -i dog.jpg. Iam not sure if i missing anything

**Comment by chintan5750** [comment]
it was due to python 3.. modified code to support python 3 and its working now

**Comment by chriskaschner** [comment]
@chintan5750 can you shed any light on what was giving you issues?

**Comment by AGrosserHH** [comment]
Any update on this?

**Comment by kt-smitha** [comment]
> it was due to python 3.. modified code to support python 3 and its working now

Could you please tell what is the changes that you made ?

**Comment by andreasmarxer** [comment]
Did anyone found out what to change?

@chintan5750 @chriskaschner @AGrosserHH @kt-smitha

**Comment by SteveIb** [comment]
did you manage to solve it? i tried with python 3 and 2. but still getting ZeroDivisionError: float division by zero on function bbox_iou while running predict.py and on training after early stopping
@chintan5750 @chriskaschner @AGrosserHH @kt-smitha @andreasmarxer
